
DROP TABLE ARTISTS_MUSICSTYLES IF EXISTS;

DROP TABLE FESTIVALS_FESTIVALSTYLES IF EXISTS;

DROP TABLE FESTIVALSTYLES IF EXISTS;

DROP TABLE CONCERTS IF EXISTS;

DROP TABLE FESTIVALS IF EXISTS;

DROP TABLE MUSICSTYLES IF EXISTS;

DROP TABLE ARTISTS IF EXISTS;

DROP TABLE POSITIONS IF EXISTS;

CREATE TABLE ARTISTS (
  ID INTEGER AUTO_INCREMENT,
  NAME VARCHAR(50),
  DESCRIPTION  VARCHAR(250),
  PRIMARY KEY(ID)
);

CREATE TABLE MUSICSTYLES (
  ID INTEGER AUTO_INCREMENT,
  STYLE VARCHAR(50),
  ARTIST_ID INTEGER REFERENCES ARTISTS(ID),
  PRIMARY KEY(ID)
);

/*CREATE TABLE POSITIONS (
  ID INTEGER AUTO_INCREMENT,
  X DOUBLE,
  Y DOUBLE,
  CITY VARCHAR(60),
  DESCRIPTION VARCHAR(700),
  PRIMARY KEY(ID)
);*/

CREATE TABLE FESTIVALS (
  ID INTEGER AUTO_INCREMENT,
  POSITION_ID INTEGER REFERENCES POSITIONS(ID),
  BEGINDATE DATE,
  ENDDATE DATE,
  NAME VARCHAR(90),
  DESCRIPTION VARCHAR(700),
  PRIMARY KEY(ID)
);

CREATE TABLE FESTIVALSTYLES (
  ID INTEGER AUTO_INCREMENT,
  STYLE VARCHAR(50),
  FESTIVAL_ID INTEGER REFERENCES FESTIVALS(ID),
  PRIMARY KEY(ID)
);

CREATE TABLE CONCERTS (
  ID INTEGER AUTO_INCREMENT,
  ARTIST_ID INTEGER REFERENCES ARTISTS(ID),
  FESTIVAL_ID INTEGER REFERENCES FESTIVALS(ID),
  BEGINDATE DATE,
  PRIMARY KEY(ID)
);
