
DROP TABLE ARTISTS_MUSICSTYLES IF EXISTS;

DROP TABLE FESTIVALS_FESTIVALSTYLES IF EXISTS;

DROP TABLE FESTIVALSTYLES IF EXISTS;

DROP TABLE CONCERTS IF EXISTS;

DROP TABLE FESTIVALS IF EXISTS;

DROP TABLE MUSICSTYLES IF EXISTS;

DROP TABLE ARTISTS IF EXISTS;

DROP TABLE POSITIONS IF EXISTS;

CREATE TABLE ARTISTS (
  id INTEGER AUTO_INCREMENT,
  NAME VARCHAR(50),
  DESCRIPTION  VARCHAR(250),
  PRIMARY KEY(id)
);

CREATE TABLE MUSICSTYLES (
  id INTEGER AUTO_INCREMENT,
  STYLE VARCHAR(50),
  ARTIST_ID INTEGER REFERENCES ARTISTS(id),
  PRIMARY KEY(id)
);

/*CREATE TABLE POSITIONS (
  id INTEGER AUTO_INCREMENT,
  X DOUBLE,
  Y DOUBLE,
  CITY VARCHAR(60),
  DESCRIPTION VARCHAR(700),
  PRIMARY KEY(id)
);*/

CREATE TABLE FESTIVALS (
  id INTEGER AUTO_INCREMENT,
  POSITION_ID INTEGER REFERENCES POSITIONS(id),
  BEGINDATE DATE,
  ENDDATE DATE,
  NAME VARCHAR(90),
  DESCRIPTION VARCHAR(700),
  PRIMARY KEY(id)
);

CREATE TABLE FESTIVALSTYLES (
  id INTEGER AUTO_INCREMENT,
  STYLE VARCHAR(50),
  FESTIVAL_ID INTEGER REFERENCES FESTIVALS(id),
  PRIMARY KEY(id)
);

CREATE TABLE CONCERTS (
  id INTEGER AUTO_INCREMENT,
  ARTIST_ID INTEGER REFERENCES ARTISTS(id),
  FESTIVAL_ID INTEGER REFERENCES FESTIVALS(id),
  BEGINDATE DATE,
  PRIMARY KEY(id)
);
