INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo1', 'Fellepo1 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo2', 'Fellepo2 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo3', 'Fellepo3 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo4', 'Fellepo4 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo5', 'Fellepo5 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo6', 'Fellepo6 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo7', 'Fellepo7 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo8', 'Fellepo8 leiras');

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Rock', (SELECT id FROM ARTISTS WHERE NAME='Fellepo1'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Rock', (SELECT id FROM ARTISTS WHERE NAME='Fellepo2'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Pop', (SELECT id FROM ARTISTS WHERE name='Fellepo2'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Rock', (SELECT id FROM ARTISTS WHERE name='Fellepo3'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Metal', (SELECT id FROM ARTISTS WHERE name='Fellepo3'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Punk', (SELECT id FROM ARTISTS WHERE name='Fellepo3'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Rock', (SELECT id FROM ARTISTS WHERE name='Fellepo4'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Folk', (SELECT id FROM ARTISTS WHERE name='Fellepo4'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Reggae', (SELECT id FROM ARTISTS WHERE name='Fellepo8'));

INSERT INTO POSITIONS(X, Y, CITY, DESCRIPTION) VALUES ( 48.217,20.300, 'Ózd', 'FesztivalPos');

INSERT INTO POSITIONS(X, Y, CITY, DESCRIPTION) VALUES ( 48.333, 21.133, 'Encs', 'FestPos');

INSERT INTO FESTIVALS(POSITION_ID, BEGINDATE, ENDDATE, NAME, DESCRIPTION) VALUES ((SELECT id FROM POSITIONS WHERE CITY='Ózd' and DESCRIPTION='FesztivalPos'), '2017-10-23', '2017-11-14', 'ÓzdFest', 'Ózd legjobb fesztiválja');

INSERT INTO FESTIVALS(POSITION_ID, BEGINDATE, ENDDATE, NAME, DESCRIPTION) VALUES ((SELECT id FROM POSITIONS WHERE CITY='Encs' and DESCRIPTION='FestPos'), '2017-12-11', '2017-12-14', 'EncsFest', 'Encs legjobb fesztiválja');

INSERT INTO FESTIVALSTYLES(STYLE, FESTIVAL_ID) VALUES ('Street-food', (SELECT id FROM FESTIVALS WHERE name='ÓzdFest'));

INSERT INTO FESTIVALSTYLES(STYLE, FESTIVAL_ID) VALUES ('Beer', (SELECT id FROM FESTIVALS WHERE name='ÓzdFest'));

INSERT INTO FESTIVALSTYLES(STYLE, FESTIVAL_ID) VALUES ('Street-food', (SELECT id FROM FESTIVALS WHERE name='EncsFest'));

INSERT INTO FESTIVALSTYLES(STYLE, FESTIVAL_ID) VALUES ('Pálinka', (SELECT id FROM FESTIVALS WHERE name='EncsFest'));

INSERT INTO USERS (USERNAME, PASSWORD, Role) VALUES ('admin@aa.hu', '123Asd7as', 'USER');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT id FROM ARTISTS WHERE name='Fellepo3'), (SELECT id FROM FESTIVALS WHERE name='ÓzdFest'), '2017-11-14');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT id FROM ARTISTS WHERE name='Fellepo2'), (SELECT id FROM FESTIVALS WHERE name='ÓzdFest'), '2017-11-15');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT id FROM ARTISTS WHERE name='Fellepo3'), (SELECT id FROM FESTIVALS WHERE name='EncsFest'), '2017-11-12');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT id FROM ARTISTS WHERE name='Fellepo1'), (SELECT id FROM FESTIVALS WHERE name='ÓzdFest'), '2017-11-14');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT id FROM ARTISTS WHERE name='Fellepo4'), (SELECT id FROM FESTIVALS WHERE name='EncsFest'), '2017-11-14');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT id FROM ARTISTS WHERE name='Fellepo7'), (SELECT id FROM FESTIVALS WHERE name='ÓzdFest'), '2017-11-14');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT id FROM ARTISTS WHERE name='Fellepo8'), (SELECT id FROM FESTIVALS WHERE name='ÓzdFest'), '2017-11-14');

INSERT INTO POSITIONS(X, Y, CITY, DESCRIPTION) VALUES ( 46.840,16.844, 'Zalaegerszeg', 'Hotel1');

INSERT INTO POSITIONS(X, Y, CITY, DESCRIPTION) VALUES ( 46.783,16.833, 'Bocfölde', 'Hotel3');

INSERT INTO POSITIONS(X, Y, CITY, DESCRIPTION) VALUES ( 46.934,16.855, 'Egervár', 'Hotel2');

INSERT INTO POSITIONS(X, Y, CITY, DESCRIPTION) VALUES ( 48.211,20.310, 'Ózd', 'Hotel4');

INSERT INTO POSITIONS(X, Y, CITY, DESCRIPTION) VALUES ( 48.221,20.306, 'Ózd', 'Hotel5');

INSERT INTO POSITIONS(X, Y, CITY, DESCRIPTION) VALUES ( 48.209,20.301, 'Ózd', 'Hotel6');

INSERT INTO ACCOMMONDATION(ADDRESS_ID, NAME, PRICE, HEADS, DESCRIPTION, EMAIL, PHONENUMBER, WEBSITE) VALUES ((SELECT id FROM POSITIONS WHERE CITY='Zalaegerszeg' and DESCRIPTION='Hotel1'),
 'Aranybárány Hotel', 1111, 111, 'Zeg legelitebb szállodája', 'arany@barany.hu', '4122334455', 'http://aranybarany.hu/hu/');

INSERT INTO ACCOMMONDATION(ADDRESS_ID, NAME, PRICE, HEADS, DESCRIPTION, EMAIL, PHONENUMBER, WEBSITE) VALUES ((SELECT id FROM POSITIONS WHERE CITY='Encs' and DESCRIPTION='FestPos'),
 'Ezüstbirka Hotel', 1121, 115, 'Encs legelitebb szállodája', 'ezust@barany.hu', '1122314455', 'http://ezustbirka.hu/');

INSERT INTO ACCOMMONDATION(ADDRESS_ID, NAME, PRICE, HEADS, DESCRIPTION, EMAIL, PHONENUMBER, WEBSITE) VALUES ((SELECT id FROM POSITIONS WHERE CITY='Ózd' and DESCRIPTION='Hotel4'),
 'Platinamarha Kemping', 1221, 511, 'Ózd legelitebb kempingje', 'platina@marha.hu', '1122344457', 'http://platinamarha.hu/');

INSERT INTO ACCOMMONDATION(ADDRESS_ID, NAME, PRICE, HEADS, DESCRIPTION, EMAIL, PHONENUMBER, WEBSITE) VALUES ((SELECT id FROM POSITIONS WHERE CITY='Ózd' and DESCRIPTION='Hotel5'),
 'Platinamarha Hotel', 1221, 511, 'Ózd legelitebb szállodája', 'platina@marha.hu', '1122334451', 'http://platinamarha.hu/');

INSERT INTO ACCOMMONDATION(ADDRESS_ID, NAME, PRICE, HEADS, DESCRIPTION, EMAIL, PHONENUMBER, WEBSITE) VALUES ((SELECT id FROM POSITIONS WHERE CITY='Ózd' and DESCRIPTION='Hotel6'),
 'A Hotel', 1221, 511, 'Ózd legelitebb szállodája', 'a@hotel.hu', '1122334459', 'http://ahotel.hu/');

INSERT INTO ACCOMMONDATION(ADDRESS_ID, NAME, PRICE, HEADS, DESCRIPTION, EMAIL, PHONENUMBER, WEBSITE) VALUES ((SELECT id FROM POSITIONS WHERE CITY='Ózd' and DESCRIPTION='FesztivalPos'),
 'B Kollégium', 1221, 511, 'Ózd legelitebb Kollégiuma', 'koli@b.hu', '1122394455', 'http://bkoli.hu/');