INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo1', 'Fellepo1 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo2', 'Fellepo2 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo3', 'Fellepo3 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo4', 'Fellepo4 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo5', 'Fellepo5 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo6', 'Fellepo6 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo7', 'Fellepo7 leiras');

INSERT INTO ARTISTS(NAME, DESCRIPTION) VALUES ('Fellepo8', 'Fellepo8 leiras');

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Rock', (SELECT ID FROM ARTISTS WHERE NAME='Fellepo1'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Rock', (SELECT ID FROM ARTISTS WHERE NAME='Fellepo2'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Pop', (SELECT ID FROM ARTISTS WHERE name='Fellepo2'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Rock', (SELECT ID FROM ARTISTS WHERE name='Fellepo3'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Metal', (SELECT ID FROM ARTISTS WHERE name='Fellepo3'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Punk', (SELECT ID FROM ARTISTS WHERE name='Fellepo3'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Rock', (SELECT ID FROM ARTISTS WHERE name='Fellepo4'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Folk', (SELECT ID FROM ARTISTS WHERE name='Fellepo4'));

INSERT INTO MUSICSTYLES(STYLE, ARTIST_ID) VALUES ('Reggae', (SELECT ID FROM ARTISTS WHERE name='Fellepo8'));

INSERT INTO POSITIONS(X, Y, CITY, DESCRIPTION) VALUES ( 55.432, 34.345, 'Ózd', 'valahol a varosban');

INSERT INTO POSITIONS(X, Y, CITY, DESCRIPTION) VALUES ( 53.432, 31.395, 'Encs', 'mashol a varosban');

INSERT INTO FESTIVALS(POSITION_ID, BEGINDATE, ENDDATE, NAME, DESCRIPTION) VALUES ((SELECT ID FROM POSITIONS WHERE CITY='Ózd'), CURRENT_DATE(), '2017-11-14', 'ÓzdFest', 'Ózd legjobb fesztiválja');

INSERT INTO FESTIVALS(POSITION_ID, BEGINDATE, ENDDATE, NAME, DESCRIPTION) VALUES ((SELECT ID FROM POSITIONS WHERE CITY='Encs'), '2017-12-11', '2017-12-14', 'EncsFest', 'Encs legjobb fesztiválja');

INSERT INTO FESTIVALSTYLES(STYLE, FESTIVAL_ID) VALUES ('Street-food', (SELECT ID FROM FESTIVALS WHERE name='ÓzdFest'));

INSERT INTO FESTIVALSTYLES(STYLE, FESTIVAL_ID) VALUES ('Beer', (SELECT ID FROM FESTIVALS WHERE name='ÓzdFest'));

INSERT INTO FESTIVALSTYLES(STYLE, FESTIVAL_ID) VALUES ('Street-food', (SELECT ID FROM FESTIVALS WHERE name='EncsFest'));

INSERT INTO FESTIVALSTYLES(STYLE, FESTIVAL_ID) VALUES ('Pálinka', (SELECT ID FROM FESTIVALS WHERE name='EncsFest'));

INSERT INTO USERS (USERNAME, PASSWORD, Role) VALUES ('admin@aa.hu', '123Asd7as', 'USER');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT ID FROM ARTISTS WHERE name='Fellepo3'), (SELECT ID FROM FESTIVALS WHERE name='ÓzdFest'), '2017-11-14');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT ID FROM ARTISTS WHERE name='Fellepo2'), (SELECT ID FROM FESTIVALS WHERE name='ÓzdFest'), '2017-11-15');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT ID FROM ARTISTS WHERE name='Fellepo3'), (SELECT ID FROM FESTIVALS WHERE name='EncsFest'), '2017-11-12');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT ID FROM ARTISTS WHERE name='Fellepo1'), (SELECT ID FROM FESTIVALS WHERE name='ÓzdFest'), '2017-11-14');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT ID FROM ARTISTS WHERE name='Fellepo4'), (SELECT ID FROM FESTIVALS WHERE name='EncsFest'), '2017-11-14');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT ID FROM ARTISTS WHERE name='Fellepo7'), (SELECT ID FROM FESTIVALS WHERE name='ÓzdFest'), '2017-11-14');

INSERT INTO CONCERTS (artist_id, festival_id, beginDate) values ((SELECT ID FROM ARTISTS WHERE name='Fellepo8'), (SELECT ID FROM FESTIVALS WHERE name='ÓzdFest'), '2017-11-14');
