--DROP TABLE ARTISTS_MUSICSTYLES IF EXISTS;

DROP TABLE FESTIVALSTYLES IF EXISTS;

DROP TABLE CONCERTS IF EXISTS;

DROP TABLE MUSICSTYLES IF EXISTS;

DROP TABLE ARTISTS IF EXISTS;

DROP TABLE FESTIVALS IF EXISTS;

DROP TABLE POSITIONS IF EXISTS;

CREATE TABLE ARTISTS (
  ID INTEGER,
  NAME VARCHAR(50),
  DESCRIPTION  VARCHAR(250),
  PRIMARY KEY(ID)
);

CREATE TABLE MUSICSTYLES (
  ID INTEGER,
  STYLE VARCHAR(50),
  FK_ARTIST INTEGER FOREIGN KEY REFERENCES ARTISTS(ID),
  PRIMARY KEY(ID)
);

CREATE TABLE POSITIONS (
  ID INTEGER,
  X DOUBLE,
  Y DOUBLE,
  CITY VARCHAR(60),
  DESCRIPTION VARCHAR(700),
  PRIMARY KEY(ID)
);

CREATE TABLE FESTIVALS (
  ID INTEGER,
  POSITION INTEGER FOREIGN KEY REFERENCES POSITIONS(ID),
  BEGINDATE DATE,
  ENDDATE DATE,
  NAME VARCHAR(90),
  DESCRIPTION VARCHAR(700),
  PRIMARY KEY(ID)
);

CREATE TABLE FESTIVALSTYLES (
  ID INTEGER,
  STYLE VARCHAR(50),
  FK_ARTIST INTEGER FOREIGN KEY REFERENCES FESTIVALS(ID),
  PRIMARY KEY(ID)
);

CREATE TABLE CONCERTS (
  ID INTEGER,
  FK_ARTIST INTEGER FOREIGN KEY REFERENCES ARTISTS(ID),
  FK_FESTIVAL INTEGER FOREIGN KEY REFERENCES FESTIVALS(ID),
  BEGINDATE DATE,
  PRIMARY KEY(ID)
);